import { notFound } from "next/navigation";
import {  hasLocale, NextIntlClientProvider } from "next-intl";
import {  setRequestLocale } from "next-intl/server";
import { routing } from "@/i18n/routing";

import type { Metadata } from "next";
import ScrollToTop from "@/components/global/ScrollToTop";
import Banner from "@/components/shared/Banner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: LayoutProps<"/[locale]">) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  
  setRequestLocale(locale);
  return (
    <NextIntlClientProvider locale={locale}>
      <Banner />
      <ScrollToTop /> {children}
    </NextIntlClientProvider>
  );
}
